import { useQuery } from '@tanstack/react-query'
import type { Customer } from '../types/customers'

const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'Ahmed Al-Mansoori',
    nameArabic: 'أحمد المنصوري',
    mobileNo: '+971-50-1234567',
    measurements: [
      {
        id: 'm1_1',
        customerId: '1',
        date: new Date('2026-07-01'),
        lengthFl: 152,
        lengthBl: 150,
        chest: 108,
        waist: 96,
        hips: 114,
        shoulder: 48,
        sleeveLength: 64,
        neck: 42,
        openHand: 15,
        cuffling: 'Double Cuff',
        fullBody: 'Regular Fit',
        chestUp: 104,
        openFold: 'Yes',
        cuffWidth: 6,
        neckWidth: 5,
        aramHole: 24,
        sleeveHaffButton: 'Yes',
        buttonFold: 'Soft',
        fo: 'Double',
        foWidth: 3,
        frantPocketLength: 14,
        farntPocketLengthByWidth: '14x12',
        sidePocket: 'Two sides',
        mobilePocketLengthByWidth: '16x9',
      },
      {
        id: 'm1_2',
        customerId: '1',
        date: new Date('2025-06-15'),
        lengthFl: 150,
        lengthBl: 148,
        chest: 104,
        waist: 92,
        hips: 110,
        shoulder: 47,
        sleeveLength: 63,
        neck: 41,
        openHand: 14,
        cuffling: 'Single Cuff',
        fullBody: 'Regular Fit',
        chestUp: 100,
        openFold: 'No',
        cuffWidth: 5.5,
        neckWidth: 4.8,
        aramHole: 23,
        sleeveHaffButton: 'No',
        buttonFold: 'Standard',
        fo: 'Single',
        foWidth: 2.5,
        frantPocketLength: 13,
        farntPocketLengthByWidth: '13x11',
        sidePocket: 'One side',
        mobilePocketLengthByWidth: '15x8',
      },
    ],
  },
  {
    id: '2',
    name: 'Fatima Al-Farsi',
    nameArabic: 'فاطمة الفارسي',
    mobileNo: '+971-55-9876543',
    measurements: [
      {
        id: 'm2_1',
        customerId: '2',
        date: new Date('2026-05-10'),
        lengthFl: 142,
        lengthBl: 140,
        chest: 96,
        waist: 80,
        hips: 104,
        shoulder: 42,
        sleeveLength: 58,
        neck: 36,
        openHand: 12,
        cuffling: 'Standard',
        fullBody: 'Slim Fit',
        chestUp: 92,
        openFold: 'Yes',
        cuffWidth: 5,
        neckWidth: 4,
        aramHole: 21,
      },
    ],
  },
  {
    id: '3',
    name: 'Zayed Al-Hashimi',
    nameArabic: 'زايد الهاشمي',
    mobileNo: '+971-52-1112223',
    measurements: [
      {
        id: 'm3_1',
        customerId: '3',
        date: new Date('2026-07-12'),
        lengthFl: 158,
        lengthBl: 156,
        chest: 112,
        waist: 102,
        hips: 120,
        shoulder: 50,
        sleeveLength: 66,
        neck: 44,
        openHand: 16,
        cuffling: 'Double Cuff',
        fullBody: 'Loose Fit',
        chestUp: 110,
        openFold: 'Yes',
        cuffWidth: 7,
        neckWidth: 5.5,
        aramHole: 26,
        sleeveHaffButton: 'Yes',
        buttonFold: 'Hard',
        fo: 'Double',
        foWidth: 3.5,
        frantPocketLength: 15,
        farntPocketLengthByWidth: '15x13',
        sidePocket: 'Two sides',
        mobilePocketLengthByWidth: '17x10',
      },
      {
        id: 'm3_2',
        customerId: '3',
        date: new Date('2025-10-05'),
        lengthFl: 157,
        lengthBl: 155,
        chest: 110,
        waist: 100,
        hips: 118,
        shoulder: 49,
        sleeveLength: 65,
        neck: 43,
        openHand: 15.5,
        cuffling: 'Double Cuff',
        fullBody: 'Loose Fit',
        chestUp: 108,
        openFold: 'Yes',
        cuffWidth: 6.8,
        neckWidth: 5.3,
        aramHole: 25,
      },
      {
        id: 'm3_3',
        customerId: '3',
        date: new Date('2024-11-20'),
        lengthFl: 155,
        lengthBl: 153,
        chest: 106,
        waist: 96,
        hips: 114,
        shoulder: 48,
        sleeveLength: 64,
        neck: 42,
        openHand: 15,
        cuffling: 'Single Cuff',
        fullBody: 'Regular Fit',
        chestUp: 102,
        openFold: 'No',
        cuffWidth: 6,
        neckWidth: 5,
        aramHole: 24,
      },
    ],
  },
  {
    id: '4',
    name: 'Sultan Al-Mansoori',
    nameArabic: 'سلطان المنصوري',
    // Shares customer '1' (Ahmed)'s phone number — mobile numbers aren't unique.
    mobileNo: '+971-50-1234567',
    measurements: [
      {
        id: 'm4_1',
        customerId: '4',
        date: new Date('2026-06-20'),
        lengthFl: 98,
        lengthBl: 96,
        chest: 68,
        waist: 60,
        hips: 70,
        shoulder: 32,
        sleeveLength: 44,
        neck: 30,
        openHand: 9,
        cuffling: 'Standard',
      },
    ],
  },
  {
    id: '5',
    name: 'Noor Al-Hashimi',
    nameArabic: 'نور الهاشمي',
    // Shares customer '3' (Zayed)'s phone number — mobile numbers aren't unique.
    mobileNo: '+971-52-1112223',
    measurements: [],
  },
]

export function useCustomers() {
  return useQuery({
    queryKey: ['customers'],
    queryFn: async () => {
      // Mock delay to simulate API call
      await new Promise((resolve) => setTimeout(resolve, 500))
      return MOCK_CUSTOMERS
    },
    staleTime: 1000 * 60 * 5, // 5 minutes
  })
}
