-- no-transaction
-- Indexes for server-side list queries (continued in the following migrations).
--
-- Until now every list endpoint returned its whole table and the browser did
-- the filtering, so nothing but the primary keys and unique constraints was
-- ever used to look a row up. Now that filtering, sorting and paging happen in
-- Postgres, two classes of column matter:
--
--   * the join keys the list queries traverse — these carry the most weight,
--     because the invoice list's lateral aggregates run per invoice row; and
--   * the columns the tables sort and filter on by default.
--
-- Columns already covered by a UNIQUE constraint (branch.name, products.sku,
-- gift_cards.code, material_stock/product_stock's composite keys, and
-- order_stage_progress/order_stage_assignments' (order_id, stage_id) pairs,
-- whose leftmost column already serves an order_id-only lookup) are indexed
-- as a side effect of that constraint and are deliberately absent here.

-- Join keys. Postgres does not index foreign keys automatically, and each of
-- these is on the inner side of a join in the orders or invoices list query.
CREATE INDEX CONCURRENTLY IF NOT EXISTS orders_invoice_id_idx ON orders (invoice_id);
