-- A physical location. It can be a branch where customers collect finished
-- orders, a store that only holds material stock, or both — so the two
-- capabilities are independent flags rather than a single type column.
-- Deactivating a location hides it from both pickers without touching the
-- stock rows and invoices that still reference it.
CREATE TABLE branch (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name TEXT NOT NULL UNIQUE,
    receives_orders BOOLEAN NOT NULL DEFAULT TRUE,
    holds_stock BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE customers (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name TEXT NOT NULL,
    mobile_no TEXT NOT NULL,
    -- Whether this customer has agreed to receive marketing messages over
    -- WhatsApp. Defaults FALSE (opt-in, not opt-out) per WhatsApp business
    -- messaging policy.
    marketing_opt_in BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (name, mobile_no)
);

CREATE TABLE materials (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name TEXT NOT NULL,
    sku TEXT,
    unit TEXT NOT NULL DEFAULT 'meters'
);

-- A material can be stocked at more than one location (branch), so stock is
-- tracked per material/location pair rather than as a single quantity.
CREATE TABLE material_stock (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    material_id UUID NOT NULL REFERENCES materials(id),
    branch_id UUID NOT NULL REFERENCES branch(id),
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0,
    UNIQUE (material_id, branch_id)
);

-- An invoice is settled in up to two payments: an advance taken up front (at
-- invoice creation) and a final payment that clears the remaining balance
-- (when the order is received) — each may use a different payment method,
-- hence the separate advance/final payment type columns. amount_paid tracks
-- the running total paid so far; advance_amount snapshots what the advance
-- payment was, since amount_paid is overwritten to total_price once the
-- final payment settles the balance.
CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    -- A tax invoice has to carry a human-readable number and the moment it was
    -- issued. The uuidv7 primary key is neither: it is not something a customer
    -- can quote back, and invoice_date is a bare DATE, so the timestamp in the
    -- printed document's QR code would otherwise have to invent midnight.
    invoice_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    total_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    invoice_date DATE NOT NULL DEFAULT CURRENT_DATE,
    branch_id UUID REFERENCES branch(id),
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount_unit TEXT NOT NULL DEFAULT 'amount' CHECK (discount_unit IN ('amount', 'percent')),
    payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'partial', 'paid')),
    amount_paid NUMERIC(10, 2) NOT NULL DEFAULT 0,
    advance_amount NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (advance_amount >= 0),
    advance_payment_type TEXT CHECK (advance_payment_type IN ('benefit', 'cash', 'card')),
    final_payment_type TEXT CHECK (final_payment_type IN ('benefit', 'cash', 'card')),
    -- A tailoring invoice finds its customer through orders → measurements, but
    -- a sale of only products or gift cards has no orders to go through. This
    -- names the buyer directly for those; it stays NULL on ordinary invoices.
    customer_id UUID REFERENCES customers(id),
    -- A gift card is tender rather than a discount, so total_price stays the
    -- gross amount charged and this sits alongside amount_paid instead of
    -- reducing the total. It is a third settlement channel next to the advance
    -- and final payments above, so what the customer actually hands over to
    -- clear the invoice is total_price - gift_card_redeemed.
    gift_card_redeemed NUMERIC(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE measurements (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    customer_id UUID NOT NULL REFERENCES customers(id),
    measurement_date DATE NOT NULL DEFAULT CURRENT_DATE,

    length_fl NUMERIC(6, 2),
    length_bl NUMERIC(6, 2),
    chest NUMERIC(6, 2),
    waist NUMERIC(6, 2),
    hips NUMERIC(6, 2),
    shoulder NUMERIC(6, 2),
    sleeve_length NUMERIC(6, 2),
    neck NUMERIC(6, 2),
    open_hand NUMERIC(6, 2),
    cuffling TEXT,
    full_body TEXT,
    chest_up NUMERIC(6, 2),
    open_fold TEXT,
    cuff_width NUMERIC(6, 2),
    neck_width NUMERIC(6, 2),
    aram_hole NUMERIC(6, 2),
    sleeve_haff_button TEXT,
    button_fold TEXT,
    fo TEXT,
    fo_width NUMERIC(6, 2),
    frant_pocket_length NUMERIC(6, 2),
    farnt_pocket_length_by_width TEXT,
    side_pocket TEXT,
    mobile_pocket_length_by_width TEXT
);

CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    measurement_id UUID NOT NULL REFERENCES measurements(id),
    material_id UUID NOT NULL REFERENCES materials(id),
    material_amount NUMERIC(10, 2) NOT NULL,
    invoice_id UUID NOT NULL REFERENCES invoices(id),
    price NUMERIC(10, 2) NOT NULL,
    thobe_type TEXT,
    f_pocket TEXT,
    collar TEXT,
    sleeve TEXT,
    patti TEXT,
    more_details TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'received')),
    received_at TIMESTAMPTZ,
    -- Where the garment is actually made, which is not necessarily where the
    -- customer collects it (that is the invoice's branch_id). NULL until
    -- production is assigned. When the two differ the garment has to be moved
    -- between locations, which is what a `requires_delivery` stage tracks.
    production_branch_id UUID REFERENCES branch(id)
);

-- The stages a garment passes through in production. Staff edit this list, so
-- it is a table rather than more values on orders.status — same reasoning as
-- `branch`, and the same retirement rule: is_active instead of a delete, so the
-- progress rows pointing at a retired stage stay readable.
CREATE TABLE order_stages (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name TEXT NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL,
    -- Marks a stage that only applies when the garment changes location. It is
    -- treated as not applicable on an order produced where the customer
    -- collects, rather than left hanging as an unfinished step.
    requires_delivery BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Seeded in the migration rather than a dev seed, so every environment starts
-- with a usable list. Staff are free to rename, reorder, or retire these.
INSERT INTO order_stages (name, sort_order, requires_delivery) VALUES
    ('Cutting', 1, FALSE),
    ('Sewing', 2, FALSE),
    ('Finishing', 3, FALSE),
    ('Location delivery', 4, TRUE);

-- A finished order brought back for modification or repair. Each return is its
-- own record with its own pass through the stage checklist, so an order
-- repaired twice keeps both histories. `charge` is recorded for the books;
-- billing a repair through an invoice is out of scope for now, which is why
-- there is no invoice_id here.
CREATE TABLE order_repairs (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    order_id UUID NOT NULL REFERENCES orders(id),
    reason TEXT NOT NULL,
    reported_on DATE NOT NULL DEFAULT CURRENT_DATE,
    charge NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (charge >= 0),
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')),
    completed_at TIMESTAMPTZ,
    notes TEXT
);

-- Records only the stages actually acted on. The checklist itself is derived by
-- overlaying these rows onto the live `order_stages` list, so adding or
-- retiring a stage takes effect on in-flight orders with no backfill, and
-- nothing has to be seeded when an invoice creates an order.
--
-- One checklist per order, covering the original build only — a repair is
-- tracked by its own record and status (see order_repairs above), not by a
-- second pass through these stages.
CREATE TABLE order_stage_progress (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    order_id UUID NOT NULL REFERENCES orders(id),
    stage_id UUID NOT NULL REFERENCES order_stages(id),
    -- 'skipped' is how a stage that doesn't apply to this particular garment is
    -- cleared without pretending it was done. Undoing a stage deletes the row
    -- rather than storing a third 'pending' value.
    status TEXT NOT NULL CHECK (status IN ('done', 'skipped')),
    completed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Where a delivery stage delivered to. NULL on every other stage.
    location_id UUID REFERENCES branch(id),
    notes TEXT,
    UNIQUE (order_id, stage_id)
);

-- Who's responsible for a stage, independent of order_stage_progress: a stage
-- can be assigned before any work happens, so it can't be a column on rows
-- that only exist once a stage is done or skipped. One assignee at a time per
-- order/stage — assigning again overwrites rather than stacking, and there is
-- no repair_id here for the same reason order_stage_progress dropped it: a
-- repair is tracked by its own record, not a second pass through the stages.
--
-- assignee_id is TEXT rather than a foreign key because there is no local
-- user table yet (see features/users) — it is mocked pending real auth and a
-- Zitadel-backed directory. assignee_name is denormalized alongside it so a
-- past assignment still reads sensibly if that mock list ever changes.
CREATE TABLE order_stage_assignments (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    order_id UUID NOT NULL REFERENCES orders(id),
    stage_id UUID NOT NULL REFERENCES order_stages(id),
    assignee_id TEXT NOT NULL,
    assignee_name TEXT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_id, stage_id)
);

-- A finished good sold as-is, as opposed to `materials`, which are raw fabric
-- consumed by a tailoring order. A product carries a list price because it
-- sells at one; an order's price is typed in per line instead. Deactivating a
-- product retires it without disturbing the invoice lines that reference it.
CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    name TEXT NOT NULL,
    sku TEXT UNIQUE,
    unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Mirrors material_stock: a product can sit at more than one location.
CREATE TABLE product_stock (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    product_id UUID NOT NULL REFERENCES products(id),
    branch_id UUID NOT NULL REFERENCES branch(id),
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0,
    UNIQUE (product_id, branch_id)
);

-- Stored value. `balance` is decremented as the card is spent across invoices,
-- so it outlives the sale that created it. The invoice that sold a card is
-- found through invoice_items rather than duplicated here.
CREATE TABLE gift_cards (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    code TEXT NOT NULL UNIQUE,
    initial_amount NUMERIC(10, 2) NOT NULL,
    balance NUMERIC(10, 2) NOT NULL,
    customer_id UUID REFERENCES customers(id),
    expires_on DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Audit trail of every redemption; gift_cards.balance is the running total the
-- redemptions add up to.
CREATE TABLE gift_card_redemptions (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    gift_card_id UUID NOT NULL REFERENCES gift_cards(id),
    invoice_id UUID NOT NULL REFERENCES invoices(id),
    amount NUMERIC(10, 2) NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A card can only be applied once per invoice; a repeat surfaces as a 409
    -- through the unique-violation mapping in error.rs.
    UNIQUE (gift_card_id, invoice_id)
);

-- Invoice lines that are not tailoring orders. These cannot live in `orders`,
-- whose measurement_id and material_id are NOT NULL and meaningless for a
-- retail sale. branch_id records where a product line's stock came off, and is
-- NULL for a gift card, which has no stock.
CREATE TABLE invoice_items (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    invoice_id UUID NOT NULL REFERENCES invoices(id),
    kind TEXT NOT NULL CHECK (kind IN ('product', 'gift_card')),
    product_id UUID REFERENCES products(id),
    gift_card_id UUID REFERENCES gift_cards(id),
    branch_id UUID REFERENCES branch(id),
    description TEXT NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL,
    line_total NUMERIC(10, 2) NOT NULL,
    CHECK (
        (kind = 'product' AND product_id IS NOT NULL AND gift_card_id IS NULL)
        OR (kind = 'gift_card' AND gift_card_id IS NOT NULL AND product_id IS NULL)
    )
);

-- A generic outbox for anything sent to a customer over an external channel.
-- `kind` is *why* the message exists — a staff-composed marketing broadcast
-- today; a system-triggered transactional notice (e.g. an invoice receipt)
-- later — and `channel` is *how* it goes out. Both live once per campaign
-- rather than per recipient, since they're decided at compose time. Only
-- 'marketing' / 'whatsapp' are allowed today; adding a transactional kind or
-- a second channel later is an additive CHECK-constraint migration, not a
-- table redesign.
CREATE TABLE notification_campaigns (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    kind TEXT NOT NULL CHECK (kind IN ('marketing')),
    channel TEXT NOT NULL CHECK (channel IN ('whatsapp')),
    -- The single pre-approved WhatsApp template this campaign fills in. A
    -- fixed default until there is more than one template to pick from.
    template_name TEXT NOT NULL DEFAULT 'marketing_broadcast_v1',
    body TEXT NOT NULL,
    -- The staff member's auth subject (see auth.rs's AuthenticatedUser). Not
    -- a foreign key — there is no local user table yet (see features/users).
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per (campaign, customer) — the outbox proper. A future
-- transactional notification is just a second `kind` of campaign creating
-- rows here, not a new table. The status lifecycle (pending -> sent/failed)
-- is what lets a real background poller replace the stub's inline dispatch
-- later with no schema change: it only changes who flips the status.
CREATE TABLE notification_recipients (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    campaign_id UUID NOT NULL REFERENCES notification_campaigns(id),
    customer_id UUID NOT NULL REFERENCES customers(id),
    -- Snapshotted at send time so a later change to the customer's number
    -- doesn't rewrite where history says this message actually went.
    mobile_no TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'failed')),
    -- Opaque id handed back by the provider (Twilio/Meta message SID) once a
    -- real client replaces the stub. NULL until then.
    provider_message_id TEXT,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    UNIQUE (campaign_id, customer_id)
);
