-- A tax invoice has to carry a human-readable number and the moment it was
-- issued, and `invoices` had neither: the uuidv7 primary key is the only
-- identifier, and `invoice_date` is a bare DATE, so anything needing a
-- timestamp (the QR code on the printed document) would have had to invent
-- midnight. Adding an identity column rewrites the table and numbers the
-- existing rows in physical order, which for uuidv7 keys is creation order.
ALTER TABLE invoices
    ADD COLUMN invoice_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE invoices
    ADD CONSTRAINT invoices_invoice_number_key UNIQUE (invoice_number);
