import { useQuery } from '@tanstack/react-query'
import type { Order } from '../types/orders'

const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    invoice: 'INV-001',
    invoiceDate: new Date('2024-01-15'),
    customerName: 'Acme Corp',
    customerMobile: '+1-555-0101',
    measurementLink: 'https://example.com/measurement/001',
    material: 'Cotton Blend',
  },
  {
    id: '2',
    invoice: 'INV-002',
    invoiceDate: new Date('2024-01-16'),
    customerName: 'Global Textiles',
    customerMobile: '+1-555-0102',
    measurementLink: 'https://example.com/measurement/002',
    material: 'Polyester',
  },
  {
    id: '3',
    invoice: 'INV-003',
    invoiceDate: new Date('2024-01-17'),
    customerName: 'Fashion Forward Ltd',
    customerMobile: '+1-555-0103',
    measurementLink: 'https://example.com/measurement/003',
    material: 'Silk',
  },
  {
    id: '4',
    invoice: 'INV-004',
    invoiceDate: new Date('2024-01-18'),
    customerName: 'Premium Materials Inc',
    customerMobile: '+1-555-0104',
    measurementLink: 'https://example.com/measurement/004',
    material: 'Wool',
  },
  {
    id: '5',
    invoice: 'INV-005',
    invoiceDate: new Date('2024-01-19'),
    customerName: 'Urban Style Co',
    customerMobile: '+1-555-0105',
    measurementLink: 'https://example.com/measurement/005',
    material: 'Linen',
  },
  {
    id: '6',
    invoice: 'INV-006',
    invoiceDate: new Date('2024-01-20'),
    customerName: 'Casual Wear LLC',
    customerMobile: '+1-555-0106',
    measurementLink: 'https://example.com/measurement/006',
    material: 'Cotton',
  },
  {
    id: '7',
    invoice: 'INV-007',
    invoiceDate: new Date('2024-01-21'),
    customerName: 'Elite Fashion',
    customerMobile: '+1-555-0107',
    measurementLink: 'https://example.com/measurement/007',
    material: 'Satin',
  },
  {
    id: '8',
    invoice: 'INV-008',
    invoiceDate: new Date('2024-01-22'),
    customerName: 'Trend Setters',
    customerMobile: '+1-555-0108',
    measurementLink: 'https://example.com/measurement/008',
    material: 'Velvet',
  },
  {
    id: '9',
    invoice: 'INV-009',
    invoiceDate: new Date('2024-01-23'),
    customerName: 'Business Attire Co',
    customerMobile: '+1-555-0109',
    measurementLink: 'https://example.com/measurement/009',
    material: 'Tweed',
  },
  {
    id: '10',
    invoice: 'INV-010',
    invoiceDate: new Date('2024-01-24'),
    customerName: 'Eco Fabrics',
    customerMobile: '+1-555-0110',
    measurementLink: 'https://example.com/measurement/010',
    material: 'Organic Cotton',
  },
  {
    id: '11',
    invoice: 'INV-011',
    invoiceDate: new Date('2024-01-25'),
    customerName: 'Designer Studios',
    customerMobile: '+1-555-0111',
    measurementLink: 'https://example.com/measurement/011',
    material: 'Cashmere Blend',
  },
  {
    id: '12',
    invoice: 'INV-012',
    invoiceDate: new Date('2024-01-26'),
    customerName: 'Custom Creations',
    customerMobile: '+1-555-0112',
    measurementLink: 'https://example.com/measurement/012',
    material: 'Denim',
  },
  {
    id: '13',
    invoice: 'INV-013',
    invoiceDate: new Date('2024-01-27'),
    customerName: 'Luxury Goods Inc',
    customerMobile: '+1-555-0113',
    measurementLink: 'https://example.com/measurement/013',
    material: 'Lace',
  },
  {
    id: '14',
    invoice: 'INV-014',
    invoiceDate: new Date('2024-01-28'),
    customerName: 'Sports Wear Pro',
    customerMobile: '+1-555-0114',
    measurementLink: 'https://example.com/measurement/014',
    material: 'Spandex Blend',
  },
  {
    id: '15',
    invoice: 'INV-015',
    invoiceDate: new Date('2024-01-29'),
    customerName: 'Classic Apparel',
    customerMobile: '+1-555-0115',
    measurementLink: 'https://example.com/measurement/015',
    material: 'Corduroy',
  },
  {
    id: '16',
    invoice: 'INV-016',
    invoiceDate: new Date('2024-01-30'),
    customerName: 'Modern Fashion',
    customerMobile: '+1-555-0116',
    measurementLink: 'https://example.com/measurement/016',
    material: 'Bamboo Fiber',
  },
  {
    id: '17',
    invoice: 'INV-017',
    invoiceDate: new Date('2024-02-01'),
    customerName: 'Heritage Textiles',
    customerMobile: '+1-555-0117',
    measurementLink: 'https://example.com/measurement/017',
    material: 'Hemp',
  },
  {
    id: '18',
    invoice: 'INV-018',
    invoiceDate: new Date('2024-02-02'),
    customerName: 'Tech Fashion',
    customerMobile: '+1-555-0118',
    measurementLink: 'https://example.com/measurement/018',
    material: 'Microfiber',
  },
  {
    id: '19',
    invoice: 'INV-019',
    invoiceDate: new Date('2024-02-03'),
    customerName: 'Sustainable Style',
    customerMobile: '+1-555-0119',
    measurementLink: 'https://example.com/measurement/019',
    material: 'Recycled Polyester',
  },
  {
    id: '20',
    invoice: 'INV-020',
    invoiceDate: new Date('2024-02-04'),
    customerName: 'Artistic Fabrics',
    customerMobile: '+1-555-0120',
    measurementLink: 'https://example.com/measurement/020',
    material: 'Jacquard',
  },
]

export function useOrders() {
  return useQuery({
    queryKey: ['orders'],
    queryFn: async () => {
      // Mock delay to simulate API call
      await new Promise((resolve) => setTimeout(resolve, 500))
      return MOCK_ORDERS
    },
    staleTime: 1000 * 60 * 5, // 5 minutes
  })
}
