/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOrderStagesIndexRouteImport } from './routes/_authenticated/order-stages/index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing/index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedGiftCardsIndexRouteImport } from './routes/_authenticated/gift-cards/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedOrderStagesNewRouteImport } from './routes/_authenticated/order-stages/new'
import { Route as AuthenticatedMarketingNewRouteImport } from './routes/_authenticated/marketing/new'
import { Route as AuthenticatedLocationsNewRouteImport } from './routes/_authenticated/locations/new'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory/new'
import { Route as AuthenticatedGiftCardsNewRouteImport } from './routes/_authenticated/gift-cards/new'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedProductsProductIdEditRouteImport } from './routes/_authenticated/products/$productId/edit'
import { Route as AuthenticatedOrderStagesStageIdEditRouteImport } from './routes/_authenticated/order-stages/$stageId/edit'
import { Route as AuthenticatedLocationsLocationIdEditRouteImport } from './routes/_authenticated/locations/$locationId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderStagesIndexRoute =
  AuthenticatedOrderStagesIndexRouteImport.update({
    id: '/order-stages/',
    path: '/order-stages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGiftCardsIndexRoute =
  AuthenticatedGiftCardsIndexRouteImport.update({
    id: '/gift-cards/',
    path: '/gift-cards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderStagesNewRoute =
  AuthenticatedOrderStagesNewRouteImport.update({
    id: '/order-stages/new',
    path: '/order-stages/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingNewRoute =
  AuthenticatedMarketingNewRouteImport.update({
    id: '/marketing/new',
    path: '/marketing/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsNewRoute =
  AuthenticatedLocationsNewRouteImport.update({
    id: '/locations/new',
    path: '/locations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGiftCardsNewRoute =
  AuthenticatedGiftCardsNewRouteImport.update({
    id: '/gift-cards/new',
    path: '/gift-cards/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsProductIdEditRoute =
  AuthenticatedProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrderStagesStageIdEditRoute =
  AuthenticatedOrderStagesStageIdEditRouteImport.update({
    id: '/order-stages/$stageId/edit',
    path: '/order-stages/$stageId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsLocationIdEditRoute =
  AuthenticatedLocationsLocationIdEditRouteImport.update({
    id: '/locations/$locationId/edit',
    path: '/locations/$locationId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/gift-cards/new': typeof AuthenticatedGiftCardsNewRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/marketing/new': typeof AuthenticatedMarketingNewRoute
  '/order-stages/new': typeof AuthenticatedOrderStagesNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/gift-cards/': typeof AuthenticatedGiftCardsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/order-stages/': typeof AuthenticatedOrderStagesIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/order-stages/$stageId/edit': typeof AuthenticatedOrderStagesStageIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/gift-cards/new': typeof AuthenticatedGiftCardsNewRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/marketing/new': typeof AuthenticatedMarketingNewRoute
  '/order-stages/new': typeof AuthenticatedOrderStagesNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/gift-cards': typeof AuthenticatedGiftCardsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/order-stages': typeof AuthenticatedOrderStagesIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/order-stages/$stageId/edit': typeof AuthenticatedOrderStagesStageIdEditRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/gift-cards/new': typeof AuthenticatedGiftCardsNewRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/locations/new': typeof AuthenticatedLocationsNewRoute
  '/_authenticated/marketing/new': typeof AuthenticatedMarketingNewRoute
  '/_authenticated/order-stages/new': typeof AuthenticatedOrderStagesNewRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/gift-cards/': typeof AuthenticatedGiftCardsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/order-stages/': typeof AuthenticatedOrderStagesIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/locations/$locationId/edit': typeof AuthenticatedLocationsLocationIdEditRoute
  '/_authenticated/order-stages/$stageId/edit': typeof AuthenticatedOrderStagesStageIdEditRoute
  '/_authenticated/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/orders'
    | '/users'
    | '/customers/new'
    | '/gift-cards/new'
    | '/inventory/new'
    | '/invoices/new'
    | '/locations/new'
    | '/marketing/new'
    | '/order-stages/new'
    | '/products/new'
    | '/customers/'
    | '/gift-cards/'
    | '/inventory/'
    | '/invoices/'
    | '/locations/'
    | '/marketing/'
    | '/order-stages/'
    | '/products/'
    | '/locations/$locationId/edit'
    | '/order-stages/$stageId/edit'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/orders'
    | '/users'
    | '/customers/new'
    | '/gift-cards/new'
    | '/inventory/new'
    | '/invoices/new'
    | '/locations/new'
    | '/marketing/new'
    | '/order-stages/new'
    | '/products/new'
    | '/customers'
    | '/gift-cards'
    | '/inventory'
    | '/invoices'
    | '/locations'
    | '/marketing'
    | '/order-stages'
    | '/products'
    | '/locations/$locationId/edit'
    | '/order-stages/$stageId/edit'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/users'
    | '/_authenticated/customers/new'
    | '/_authenticated/gift-cards/new'
    | '/_authenticated/inventory/new'
    | '/_authenticated/invoices/new'
    | '/_authenticated/locations/new'
    | '/_authenticated/marketing/new'
    | '/_authenticated/order-stages/new'
    | '/_authenticated/products/new'
    | '/_authenticated/customers/'
    | '/_authenticated/gift-cards/'
    | '/_authenticated/inventory/'
    | '/_authenticated/invoices/'
    | '/_authenticated/locations/'
    | '/_authenticated/marketing/'
    | '/_authenticated/order-stages/'
    | '/_authenticated/products/'
    | '/_authenticated/locations/$locationId/edit'
    | '/_authenticated/order-stages/$stageId/edit'
    | '/_authenticated/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-stages/': {
      id: '/_authenticated/order-stages/'
      path: '/order-stages'
      fullPath: '/order-stages/'
      preLoaderRoute: typeof AuthenticatedOrderStagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gift-cards/': {
      id: '/_authenticated/gift-cards/'
      path: '/gift-cards'
      fullPath: '/gift-cards/'
      preLoaderRoute: typeof AuthenticatedGiftCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-stages/new': {
      id: '/_authenticated/order-stages/new'
      path: '/order-stages/new'
      fullPath: '/order-stages/new'
      preLoaderRoute: typeof AuthenticatedOrderStagesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/new': {
      id: '/_authenticated/marketing/new'
      path: '/marketing/new'
      fullPath: '/marketing/new'
      preLoaderRoute: typeof AuthenticatedMarketingNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/new': {
      id: '/_authenticated/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedLocationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gift-cards/new': {
      id: '/_authenticated/gift-cards/new'
      path: '/gift-cards/new'
      fullPath: '/gift-cards/new'
      preLoaderRoute: typeof AuthenticatedGiftCardsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$productId/edit': {
      id: '/_authenticated/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/order-stages/$stageId/edit': {
      id: '/_authenticated/order-stages/$stageId/edit'
      path: '/order-stages/$stageId/edit'
      fullPath: '/order-stages/$stageId/edit'
      preLoaderRoute: typeof AuthenticatedOrderStagesStageIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/$locationId/edit': {
      id: '/_authenticated/locations/$locationId/edit'
      path: '/locations/$locationId/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof AuthenticatedLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedGiftCardsNewRoute: typeof AuthenticatedGiftCardsNewRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedLocationsNewRoute: typeof AuthenticatedLocationsNewRoute
  AuthenticatedMarketingNewRoute: typeof AuthenticatedMarketingNewRoute
  AuthenticatedOrderStagesNewRoute: typeof AuthenticatedOrderStagesNewRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedGiftCardsIndexRoute: typeof AuthenticatedGiftCardsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedOrderStagesIndexRoute: typeof AuthenticatedOrderStagesIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedLocationsLocationIdEditRoute: typeof AuthenticatedLocationsLocationIdEditRoute
  AuthenticatedOrderStagesStageIdEditRoute: typeof AuthenticatedOrderStagesStageIdEditRoute
  AuthenticatedProductsProductIdEditRoute: typeof AuthenticatedProductsProductIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedGiftCardsNewRoute: AuthenticatedGiftCardsNewRoute,
  AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedLocationsNewRoute: AuthenticatedLocationsNewRoute,
  AuthenticatedMarketingNewRoute: AuthenticatedMarketingNewRoute,
  AuthenticatedOrderStagesNewRoute: AuthenticatedOrderStagesNewRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedGiftCardsIndexRoute: AuthenticatedGiftCardsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  AuthenticatedOrderStagesIndexRoute: AuthenticatedOrderStagesIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedLocationsLocationIdEditRoute:
    AuthenticatedLocationsLocationIdEditRoute,
  AuthenticatedOrderStagesStageIdEditRoute:
    AuthenticatedOrderStagesStageIdEditRoute,
  AuthenticatedProductsProductIdEditRoute:
    AuthenticatedProductsProductIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
