// GENERATED by scripts/fabric-designs/assets.py from Desion.pdf — do not edit.
// The section keys are the backend orders column slugs:
//   neck = collar, sleeve = sleeve, front_pocket = fPocket,
//   patti = patti, thob_type = thobeType.
//
// Re-run the generator from the repo root after any extraction change:
//   python3 scripts/fabric-designs/extract.py && python3 scripts/fabric-designs/assets.py

export interface ThobDesignOption {
  id: string
  label: string
  image: string
}

export const NECK: ThobDesignOption[] = [
  { id: '1', label: '1', image: '/designs/neck/01-1.webp' },
  { id: '1-n-1-b', label: '1 - N.1.B', image: '/designs/neck/02-1-n-1-b.webp' },
  { id: '1-n-1-t', label: '1 - N.1.T', image: '/designs/neck/03-1-n-1-t.webp' },
  { id: '2', label: '2', image: '/designs/neck/04-2.webp' },
  { id: '3', label: '3', image: '/designs/neck/05-3.webp' },
  { id: '3-n-2-b', label: '3 - N.2.B', image: '/designs/neck/06-3-n-2-b.webp' },
  { id: '3-n-2-t', label: '3 - N.2.T', image: '/designs/neck/07-3-n-2-t.webp' },
  { id: '4', label: '4', image: '/designs/neck/08-4.webp' },
  { id: '4-n-1-b', label: '4 - N.1.B', image: '/designs/neck/09-4-n-1-b.webp' },
  { id: '4-n-1-h', label: '4 - N.1.H', image: '/designs/neck/10-4-n-1-h.webp' },
  { id: '5', label: '5', image: '/designs/neck/11-5.webp' },
  { id: '5-n-2-b', label: '5 N.2.B', image: '/designs/neck/12-5-n-2-b.webp' },
  { id: '5-n-2-h', label: '5 - N.2.H', image: '/designs/neck/13-5-n-2-h.webp' },
  { id: '5-n-2-t', label: '5 - N.2.T', image: '/designs/neck/14-5-n-2-t.webp' },
  { id: '6', label: '6', image: '/designs/neck/15-6.webp' },
  { id: '6-n-2-b', label: '6 - N.2.B', image: '/designs/neck/16-6-n-2-b.webp' },
  { id: '6-n-2-h', label: '6 - N.2.H', image: '/designs/neck/17-6-n-2-h.webp' },
  { id: '7', label: '7', image: '/designs/neck/18-7.webp' },
  { id: '7-n-1-h', label: '7 - N.1.H', image: '/designs/neck/19-7-n-1-h.webp' },
  { id: '7-n-1-b', label: '7 - N.1.B', image: '/designs/neck/20-7-n-1-b.webp' },
  { id: '7-n-2-b', label: '7 - N.2.B', image: '/designs/neck/21-7-n-2-b.webp' },
  { id: '7-n-1-t', label: '7 - N.1.T', image: '/designs/neck/22-7-n-1-t.webp' },
  { id: '8', label: '8', image: '/designs/neck/23-8.webp' },
  { id: '9', label: '9', image: '/designs/neck/24-9.webp' },
  { id: '9-n-2-b', label: '9 - N.2.B', image: '/designs/neck/25-9-n-2-b.webp' },
  { id: '10', label: '10', image: '/designs/neck/26-10.webp' },
  { id: '11', label: '11', image: '/designs/neck/27-11.webp' },
  { id: '12', label: '12', image: '/designs/neck/28-12.webp' },
  { id: 'china', label: 'CHINA', image: '/designs/neck/29-china.webp' },
  {
    id: 'new-shirt-collor',
    label: 'NEW SHIRT COLLOR',
    image: '/designs/neck/30-new-shirt-collor.webp',
  },
  { id: 'normal', label: 'NORMAL', image: '/designs/neck/31-normal.webp' },
]

export const SLEEVE: ThobDesignOption[] = [
  { id: '1', label: '1', image: '/designs/sleeve/01-1.webp' },
  { id: '2', label: '2', image: '/designs/sleeve/02-2.webp' },
  { id: '2-thobx', label: '2 THOBX', image: '/designs/sleeve/03-2-thobx.webp' },
  { id: '3', label: '3', image: '/designs/sleeve/04-3.webp' },
  { id: '4', label: '4', image: '/designs/sleeve/05-4.webp' },
  { id: '5', label: '5', image: '/designs/sleeve/06-5.webp' },
  { id: '5-thobx', label: '5 Thobx', image: '/designs/sleeve/07-5-thobx.webp' },
  { id: '6', label: '6', image: '/designs/sleeve/08-6.webp' },
  { id: '6-thobx', label: '6 THOBX', image: '/designs/sleeve/09-6-thobx.webp' },
  {
    id: 'double-cuff',
    label: 'Double Cuff',
    image: '/designs/sleeve/10-double-cuff.webp',
  },
  {
    id: 'double-cuff-thobx',
    label: 'Double Cuff Thobx',
    image: '/designs/sleeve/11-double-cuff-thobx.webp',
  },
  { id: 'open', label: 'Open', image: '/designs/sleeve/12-open.webp' },
  { id: 'cuff', label: 'Cuff', image: '/designs/sleeve/13-cuff.webp' },
]

export const FRONT_POCKET: ThobDesignOption[] = [
  {
    id: 'cross-inside',
    label: 'Cross Inside',
    image: '/designs/front_pocket/01-cross-inside.webp',
  },
  {
    id: 'cross-clip',
    label: 'Cross Clip',
    image: '/designs/front_pocket/02-cross-clip.webp',
  },
  { id: 'round', label: 'Round', image: '/designs/front_pocket/03-round.webp' },
  {
    id: 'round-clip',
    label: 'Round Clip',
    image: '/designs/front_pocket/04-round-clip.webp',
  },
  {
    id: 'straight',
    label: 'Straight',
    image: '/designs/front_pocket/05-straight.webp',
  },
  {
    id: 'straight-clip',
    label: 'Straight Clip',
    image: '/designs/front_pocket/06-straight-clip.webp',
  },
  { id: 'v', label: 'v', image: '/designs/front_pocket/07-v.webp' },
  {
    id: 'v-clip',
    label: 'V Clip',
    image: '/designs/front_pocket/08-v-clip.webp',
  },
  { id: 'volut', label: 'Volut', image: '/designs/front_pocket/09-volut.webp' },
  { id: 'm', label: 'M', image: '/designs/front_pocket/10-m.webp' },
  { id: 'n', label: 'N', image: '/designs/front_pocket/11-n.webp' },
  {
    id: 'normal',
    label: 'Normal',
    image: '/designs/front_pocket/12-normal.webp',
  },
  {
    id: 'cross-no-canvas',
    label: 'Cross No Canvas',
    image: '/designs/front_pocket/13-cross-no-canvas.webp',
  },
  {
    id: 'round-no-canvas',
    label: 'Round No Canvas',
    image: '/designs/front_pocket/14-round-no-canvas.webp',
  },
  { id: 'no', label: 'NO', image: '/designs/front_pocket/15-no.webp' },
]

export const PATTI: ThobDesignOption[] = [
  { id: 'zip', label: 'Zip', image: '/designs/patti/01-zip.webp' },
  {
    id: 'down-stiching-zip',
    label: 'Down Stiching = Zip',
    image: '/designs/patti/02-down-stiching-zip.webp',
  },
  {
    id: 'no-canvas-zip',
    label: 'No Canvas = Zip',
    image: '/designs/patti/03-no-canvas-zip.webp',
  },
  {
    id: 'zip-show',
    label: 'Zip + Show',
    image: '/designs/patti/04-zip-show.webp',
  },
  {
    id: 'down-stiching-zip-show',
    label: 'Down Stiching = Zip + Show',
    image: '/designs/patti/05-down-stiching-zip-show.webp',
  },
  {
    id: 'no-canvas-zip-show',
    label: 'No Canvas = Zip + Show',
    image: '/designs/patti/06-no-canvas-zip-show.webp',
  },
  {
    id: 'saudi-patti-no-canvas-zip',
    label: 'Saudi Patti - No Canvas = Zip',
    image: '/designs/patti/07-saudi-patti-no-canvas-zip.webp',
  },
  {
    id: 'inside-button',
    label: 'Inside Button',
    image: '/designs/patti/08-inside-button.webp',
  },
  {
    id: 'down-sticing-inside-button',
    label: 'Down Sticing = Inside Button',
    image: '/designs/patti/09-down-sticing-inside-button.webp',
  },
  {
    id: 'no-canvas-inside-button',
    label: 'No Canvas = Inside Button',
    image: '/designs/patti/10-no-canvas-inside-button.webp',
  },
  {
    id: 'saudi-patti-no-canvas-inside-button',
    label: 'Saudi Patti - No Canvas = Inside Button',
    image: '/designs/patti/11-saudi-patti-no-canvas-inside-button.webp',
  },
  {
    id: 'show-button',
    label: 'Show Button',
    image: '/designs/patti/12-show-button.webp',
  },
  {
    id: 'down-sticing-show-button',
    label: 'Down Sticing = Show Button',
    image: '/designs/patti/13-down-sticing-show-button.webp',
  },
  {
    id: 'no-canvas-show-button',
    label: 'No Canvas = Show Button',
    image: '/designs/patti/14-no-canvas-show-button.webp',
  },
  { id: 'normal', label: 'Normal', image: '/designs/patti/15-normal.webp' },
  {
    id: '3-show-button',
    label: '3 - Show Button',
    image: '/designs/patti/16-3-show-button.webp',
  },
  {
    id: '3-zip-show',
    label: '3 - Zip + Show',
    image: '/designs/patti/17-3-zip-show.webp',
  },
  {
    id: 'zip-thobx-steel',
    label: 'Zip + Thobx Steel',
    image: '/designs/patti/18-zip-thobx-steel.webp',
  },
  {
    id: 'zip-street',
    label: 'Zip Street',
    image: '/designs/patti/19-zip-street.webp',
  },
  {
    id: 'no-canvas-no-stitching-show-button',
    label: 'No Canvas , No Stitching = Show Button',
    image: '/designs/patti/20-no-canvas-no-stitching-show-button.webp',
  },
]

export const THOB_TYPE: ThobDesignOption[] = [
  {
    id: '9-model',
    label: '9 Model',
    image: '/designs/thob_type/01-9-model.webp',
  },
  { id: 'upline', label: 'Upline', image: '/designs/thob_type/02-upline.webp' },
  {
    id: 's-c-f-p',
    label: 'S.C.F.P',
    image: '/designs/thob_type/03-s-c-f-p.webp',
  },
  {
    id: 'back-chepsa',
    label: 'Back Chepsa',
    image: '/designs/thob_type/04-back-chepsa.webp',
  },
  {
    id: 'front-chepsa',
    label: 'Front Chepsa',
    image: '/designs/thob_type/05-front-chepsa.webp',
  },
  {
    id: 'front-back-chepsa',
    label: 'Front & Back = Chepsa',
    image: '/designs/thob_type/06-front-back-chepsa.webp',
  },
  {
    id: '9-mode-front-back-chepsa',
    label: '9 mode + Front & Back = Chepsa',
    image: '/designs/thob_type/07-9-mode-front-back-chepsa.webp',
  },
  {
    id: '9-mode-front-chepsa',
    label: '9 mode + Front Chepsa',
    image: '/designs/thob_type/08-9-mode-front-chepsa.webp',
  },
  { id: 'tatriz', label: 'Tatriz', image: '/designs/thob_type/09-tatriz.webp' },
  { id: 'normal', label: 'Normal', image: '/designs/thob_type/10-normal.webp' },
  {
    id: 'b-h-t-v',
    label: 'B.H.T.V',
    image: '/designs/thob_type/11-b-h-t-v.webp',
  },
  { id: 'hezazi', label: 'Hezazi', image: '/designs/thob_type/12-hezazi.webp' },
  { id: 'thobx', label: 'Thobx', image: '/designs/thob_type/13-thobx.webp' },
]
