#!/usr/bin/env python3
"""Build the web/served-and-printed design assets from the extracted rasters.

Reads `catalog.json` plus the rasters in `source/` (both produced by
`extract.py`) and emits:

  frontend/public/designs/<section>/<NN>-<slug>.webp   served to the order form
  frontend/src/features/invoices/data/design-catalog.ts generated options module
  backend/assets/designs/<section>/<NN>-<slug>.webp    embedded copies for the
                                                       printed invoice
  backend/src/features/invoices/designs.rs             generated list of
                                                       embedded assets + lookup

The invoice document must stay self-contained (printed from a no-origin
iframe), so the backend gets its own WebP copies embedded in the binary via
include_bytes!, never fetched at render time. The frontend serves the same
bytes from /designs for the on-screen picker.

WebP with a 512px cap keeps the binary footprint small (line art compresses
well) while staying crisp at chip sizes. Regeneration replaces every output.
(If you regenerate the frontend module, run prettier --write on it afterwards
to keep the CI formatting gate happy.)

Run from the repository root:
  python3 scripts/fabric-designs/assets.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CATALOG = HERE / "catalog.json"
SOURCE = HERE / "source"

FRONTEND_DESIGNS = ROOT / "frontend" / "public" / "designs"
FRONTEND_MODULE = ROOT / "frontend" / "src" / "features" / "invoices" / "data" / "design-catalog.ts"
BACKEND_DESIGNS = ROOT / "backend" / "assets" / "designs"
BACKEND_MODULE = ROOT / "backend" / "src" / "features" / "invoices" / "designs.rs"

# Cap the long edge so the assets stay small; chip display is never bigger
# than ~150px and the printed invoice shows ~48px.
MAX_EDGE = 512


def make_webp(src: Path, dest: Path) -> tuple[int, int]:
    img = Image.open(src).convert("RGB")
    scale = MAX_EDGE / max(img.width, img.height)
    if scale < 1:
        img = img.resize(
            (round(img.width * scale), round(img.height * scale)), Image.LANCZOS
        )
    img.save(dest, "WEBP", quality=82, method=6)
    return img.width, img.height


def main() -> int:
    if not CATALOG.exists():
        print("catalog.json missing — run extract.py first.", file=sys.stderr)
        return 1

    catalog: dict[str, list[dict]] = json.loads(CATALOG.read_text())

    # Regeneration is additive-free for every generated output.
    for stale in FRONTEND_DESIGNS.rglob("*.webp"):
        stale.unlink()
    for stale in BACKEND_DESIGNS.rglob("*.webp"):
        stale.unlink()

    frontend_options: dict[str, list[dict]] = {}
    # section, slug, label, rel path
    embedded: list[tuple[str, str, str, str]] = []

    total = 0
    for section, options in catalog.items():
        rows = []
        for opt in options:
            src = SOURCE / opt["file"]
            rel = f"{section}/{opt['file'].rsplit('/', 1)[1]}".replace(".png", ".webp")
            fd = FRONTEND_DESIGNS / rel
            bd = BACKEND_DESIGNS / rel
            fd.parent.mkdir(parents=True, exist_ok=True)
            bd.parent.mkdir(parents=True, exist_ok=True)
            make_webp(src, fd)
            bd.write_bytes(fd.read_bytes())
            rows.append(
                {
                    "id": opt["slug"],
                    "label": opt["label"],
                    "image": f"/designs/{rel}",
                }
            )
            embedded.append((section, opt["slug"], opt["label"], rel))
            total += 1
        frontend_options[section] = rows

    _write_frontend_module(frontend_options)
    _write_backend_module(embedded)
    print(f"built {total} webp assets -> {FRONTEND_DESIGNS} (+ {BACKEND_DESIGNS})")
    print(f"  frontend module: {FRONTEND_MODULE}")
    print(f"  backend module:  {BACKEND_MODULE}")
    return 0


def _write_frontend_module(options: dict[str, list[dict]]) -> None:
    blocks = []
    for section in (
        "neck",
        "sleeve",
        "front_pocket",
        "patti",
        "thob_type",
    ):
        lines = ",\n".join(
            f"    {{ id: {json.dumps(o['id'])}, "
            f"label: {json.dumps(o['label'])}, "
            f"image: {json.dumps(o['image'])} }}"
            for o in options[section]
        )
        blocks.append(
            f"export const {section.upper()}: ThobDesignOption[] = [\n{lines},\n];"
        )
    header = """// GENERATED by scripts/fabric-designs/assets.py from Desion.pdf — do not edit.
// The section keys are the backend orders column slugs:
//   neck = collar, sleeve = sleeve, front_pocket = fPocket,
//   patti = patti, thob_type = thobeType.
//
// Re-run the generator from the repo root after any extraction change, then
// normalize the formatting (the `pnpm run check` gate enforces it):
//   python3 scripts/fabric-designs/extract.py
//   python3 scripts/fabric-designs/assets.py
//   (cd frontend && pnpm exec prettier --write src/features/invoices/data/design-catalog.ts)

export interface ThobDesignOption {
  id: string
  label: string
  image: string
}

"""
    FRONTEND_MODULE.write_text(header + "\n\n".join(blocks) + "\n")


def _write_backend_module(embedded: list[tuple[str, str, str, str]]) -> None:
    entries = [
        f"    DesignAsset {{ section: {json.dumps(section)}, "
        f"slug: {json.dumps(slug)}, label: {json.dumps(label)}, "
        f"bytes: include_bytes!({json.dumps('../../../assets/designs/' + rel)}) }},"
        for section, slug, label, rel in embedded
    ]
    module = f"""//! Thob design catalog embedded for the printed invoice.
//! GENERATED by scripts/fabric-designs/assets.py from Desion.pdf — do not edit.
//!
//! The invoice document must stay self-contained, so the raster for every
//! option is compiled into the binary as a WebP and looked up by section +
//! slug at render time. Re-run the generator from the repo root after any
//! extraction change:
//!   python3 scripts/fabric-designs/extract.py && python3 scripts/fabric-designs/assets.py

pub struct DesignAsset {{
    pub section: &'static str,
    pub slug: &'static str,
    pub label: &'static str,
    pub bytes: &'static [u8],
}}

/// Every catalog option, in catalog order per section.
#[rustfmt::skip]
pub static DESIGNS: &[DesignAsset] = &[
{chr(10).join(entries)}
];
"""
    BACKEND_MODULE.write_text(module)


if __name__ == "__main__":
    sys.exit(main())